# Generated by Django 5.2.4 on 2025-07-29 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneaker',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='size_options',
        ),
        migrations.CreateModel(
            name='SneakerSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='store.sneaker')),
            ],
        ),
    ]
