# Generated by Django 5.2.4 on 2025-07-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_sneaker_price_remove_sneaker_size_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneaker',
            name='is_sold_out',
        ),
        migrations.AddField(
            model_name='sneakersize',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
