# Generated by Django 5.2.4 on 2025-07-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_sneaker_is_sold_out_sneakersize_is_sold_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakersize',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
