# Generated by Django 5.2.4 on 2025-07-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_sneakersize_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakersize',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
