# Generated by Django 5.2.4 on 2025-07-29 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_sneakersize_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SneakerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sneaker_gallery/')),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.sneaker')),
            ],
        ),
    ]
