# Generated by Django 5.2.4 on 2025-07-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_sneakerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='short_description',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
