# Generated by Django 5.2.4 on 2025-07-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_sneaker_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sneaker',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='short_description',
            field=models.TextField(blank=True, max_length=350),
        ),
    ]
