# Generated by Django 5.2.4 on 2025-07-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_sneaker_on_sale_sneaker_original_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakersize',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
