# Generated by Django 5.2.4 on 2025-08-09 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_quanity_cartitem_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('funds_held', 'Funds Held (Escrow)'), ('shipped', 'Order Shipped'), ('delivered', 'Order Delivered'), ('released', 'Funds Successfully Released to SoulSoles.co'), ('refunded', 'Refunded'), ('disputed', 'In Dispute')], default='pending_payment', max_length=30)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('tracking_number', models.CharField(blank=True, max_length=200)),
                ('courier', models.CharField(blank=True, max_length=200)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
