# Generated by Django 5.2.4 on 2025-08-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_orderitem_sourcingrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcingrequest',
            name='size',
        ),
        migrations.AddField(
            model_name='sourcingrequest',
            name='sizes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
