# Generated by Django 5.2.4 on 2025-08-19 16:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_sourcingrequest_size_sourcingrequest_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='sneakerimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
